apiVersion: policy/v1
kind: PodDisruptionBudget
metadata:
  labels:
    app: prometheus
  name: prometheus
  namespace: monitoring
spec:
  minAvailable: 1
  selector:
    matchLabels:
      app: prometheus
