version: '3.8'

services:
  app:
    build:
      context: .
      dockerfile: Dockerfile

    volumes:
      - ../..:/workspaces:cached
      - $HOME/.kube:/home/vscode/.kube
    command: sleep infinity
