---
apiVersion: v1
kind: ConfigMap
metadata:
  name: actioneer
  namespace: monitoring
  labels:
    app: actioneer
data:
  config.yaml: |-
    version: v1
    actions:
      - name: "Delete Test Pod"
        alertname: "Test Alert"
        command: "kubectl delete pod ~pod -n ~namespace"
