apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: actioneer
  name: actioneer
  namespace: monitoring
spec:
  replicas: 1
  selector:
    matchLabels:
      app: actioneer
  strategy:
  template:
    metadata:
      labels:
        app: actioneer
    spec:
      serviceAccountName: actioneer
      containers:
      - args:
          - --log-level=debug
          - --config-path=/etc/actioneer/config.yaml
        image: actioneer:v0.1.1
        name: actioneer
        ports:
          - containerPort: 8080
        volumeMounts:
          - mountPath: /etc/actioneer
            name: actioneer
      volumes:
        - configMap:
            name: actioneer
          name: actioneer
