---
apiVersion: v1
kind: ConfigMap
metadata:
  name: k8s-automaton
  namespace: monitoring
  labels:
    app: k8s-automaton
data:
  config.yaml: |-
    version: v1
    actions:
      - alertname: "Test Alert"
        command: "kubectl delete pod ~pod -n ~namespace"
