---
apiVersion: v1
kind: ServiceAccount
metadata:
  labels:
    app: k8s-automaton
  name: k8s-automaton
  namespace: monitoring
---
kind: Role
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  labels:
    app: k8s-automaton
  name: k8s-automaton-pods-delete
  namespace: monitoring
rules:
  - apiGroups:
      - ""
    resources:
      - pods
    verbs:
      - delete
---
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  labels:
    app: k8s-automaton
  name: k8s-automaton-pods-delete
  namespace: monitoring
subjects:
  - kind: ServiceAccount
    name: k8s-automaton
roleRef:
  kind: Role
  name: k8s-automaton-pods-delete
  apiGroup: rbac.authorization.k8s.io
