apiVersion: v1
kind: Service
metadata:
  labels:
    app: k8s-automaton
  name: k8s-automaton
  namespace: monitoring
spec:
  ports:
  - port: 8080
    targetPort: 8080
  selector:
    app: k8s-automaton
