name: Test and Release
on: [push]
jobs:
  Test:
    runs-on: ubuntu-latest
    steps:

      - name: Check out
        uses: actions/checkout@v3

      - name: Test
        run: ./bin/test.sh

      - name: Update coverage report
        uses: ncruces/go-coverage-report@v0.3
        if: github.ref == 'refs/heads/main'
        with:
          coverage-file: ./app/coverage.out
          report: true
          chart: true
          amend: true
