name: Test and Release
on: [push]
jobs:
  Test:
    runs-on: ubuntu-latest
    steps:
      - name: Check out
        uses: actions/checkout@v3
      - name: Test
        run: ./bin/test.sh
      - name: Update coverage report
        uses: Evedel/go-coverage-report@v0.4.0-rc1
        # if: github.ref == 'refs/heads/main'
        with:
          working-directory: ./app
